### ISSUE TITLE
Internal Error 500

### ISSUE THREAD

**Issue by DevGoran** [johanohly/AirTrail#74]
### The bug

After deploying AirTrail via Portainer, I recieve error 500 when opening the web interface

### Operating System that is running AirTrail

Docker

### AirTrail Version

latest

### Your docker-compose.yml content

```YAML
services:
  db:
    container_name: airtrail_db
    image: postgres:16-alpine
    restart: always
    env_file:
      - stack.env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    restart: always
    env_file:
      - stack.env
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
```

### Your .env content

```Shell
ORIGIN=http://hostIP:3000
DB_URL=postgres://airtrail:PASSWORD_HERE@db:5432/airtrail
DB_PASSWORD=PASSWORD_HERE
DB_DATABASE_NAME=airtrail
DB_USERNAME=airtrail
```

### Reproduction steps

1. Deploy AirTrail
2. Open Web interface

### Relevant log output

```shell
Listening on 0.0.0.0:3000
530 |         result = new this._Promise((resolve, reject) => {
531 |           query.callback = (err, res) => (err ? reject(err) : resolve(res))
532 |         }).catch((err) => {
533 |           // replace the stack trace that leads to `TCP.onStreamRead` with one that leads back to the
534 |           // application that created the query
535 |           Error.captureStackTrace(err)
                      ^
error: relation "app_config" does not exist
 code: "42P01"
      at /app/node_modules/pg/lib/client.js:535:17
      at processTicksAndRejections (native:1:1)
      at /app/node_modules/kysely/dist/esm/dialect/postgres/postgres-driver.js:104:21
```

**Comment by r1979** [comment]
+1 same error

**Comment by johanohly** [comment]
This is a known error related to the arm64 build. I will be able to fix this within a day and publish a new release.
If this isn't running on arm, please include the docker container logs.

**Comment by r1979** [comment]
```
airtrail_db  | 
airtrail_db  | PostgreSQL Database directory appears to contain a database; Skipping initialization
airtrail_db  | 
airtrail_db  | 2024-10-19 07:53:26.541 UTC [1] LOG:  starting PostgreSQL 16.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
airtrail_db  | 2024-10-19 07:53:26.541 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
airtrail_db  | 2024-10-19 07:53:26.541 UTC [1] LOG:  listening on IPv6 address "::", port 5432
airtrail_db  | 2024-10-19 07:53:26.547 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
airtrail_db  | 2024-10-19 07:53:26.551 UTC [28] LOG:  database system was interrupted; last known up at 2024-10-19 07:49:59 UTC
airtrail_db  | 2024-10-19 07:53:26.717 UTC [28] LOG:  database system was not properly shut down; automatic recovery in progress
airtrail_db  | 2024-10-19 07:53:26.719 UTC [28] LOG:  invalid record length at 0/1978C98: expected at least 24, got 0
airtrail_db  | 2024-10-19 07:53:26.719 UTC [28] LOG:  redo is not required
airtrail_db  | 2024-10-19 07:53:26.723 UTC [26] LOG:  checkpoint starting: end-of-recovery immediate wait
airtrail_db  | 2024-10-19 07:53:26.731 UTC [26] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.003 s, sync=0.002 s, total=0.010 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB; lsn=0/1978C98, redo lsn=0/1978C98
airtrail_db  | 2024-10-19 07:53:26.735 UTC [1] LOG:  database system is ready to accept connections
airtrail     | Applying migrations...
airtrail     | Resolving dependencies
airtrail     | Resolved, downloaded and extracted [26]
airtrail     | Saved lockfile
airtrail     | Starting server...
airtrail     | Listening on 0.0.0.0:3000
```

and then the error

```
airtrail_db  | 2024-10-19 07:54:26.415 UTC [107] ERROR:  relation "app_config" does not exist at character 15
airtrail_db  | 2024-10-19 07:54:26.415 UTC [107] STATEMENT:  select * from "app_config" limit $1
airtrail     | 530 |         result = new this._Promise((resolve, reject) => {
airtrail     | 531 |           query.callback = (err, res) => (err ? reject(err) : resolve(res))
airtrail     | 532 |         }).catch((err) => {
airtrail     | 533 |           // replace the stack trace that leads to `TCP.onStreamRead` with one that leads back to the
airtrail     | 534 |           // application that created the query
airtrail     | 535 |           Error.captureStackTrace(err)
airtrail     |                       ^
airtrail     | error: relation "app_config" does not exist
airtrail     |  code: "42P01"
airtrail     | 
airtrail     |       at /app/node_modules/pg/lib/client.js:535:17
airtrail     |       at processTicksAndRejections (native:1:1)
airtrail     |       at /app/node_modules/kysely/dist/esm/dialect/postgres/postgres-driver.js:104:21
airtrail     | 
```

**Comment by wkulhanek** [comment]
Same here. Not on ARM but on AMD via ProxMox LXC container.
DB Log:
`waiting for server to shut down...2024-10-19 09:05:38.354 UTC [40] LOG:  received fast shutdown request
.2024-10-19 09:05:38.358 UTC [40] LOG:  aborting any active transactions
2024-10-19 09:05:38.362 UTC [40] LOG:  background worker "logical replication launcher" (PID 46) exited with exit code 1
2024-10-19 09:05:38.362 UTC [41] LOG:  shutting down
2024-10-19 09:05:38.365 UTC [41] LOG:  checkpoint starting: shutdown immediate
2024-10-19 09:05:38.610 UTC [41] LOG:  checkpoint complete: wrote 924 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.018 s, sync=0.217 s, total=0.248 s; sync files=301, longest=0.007 s, average=0.001 s; distance=4267 kB, estimate=4267 kB; lsn=0/191AB68, redo lsn=0/191AB68
2024-10-19 09:05:38.617 UTC [40] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2024-10-19 09:05:38.679 UTC [1] LOG:  starting PostgreSQL 16.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
2024-10-19 09:05:38.679 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-10-19 09:05:38.679 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-10-19 09:05:38.687 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-10-19 09:05:38.696 UTC [56] LOG:  database system was shut down at 2024-10-19 09:05:38 UTC
2024-10-19 09:05:38.703 UTC [1] LOG:  database system is ready to accept connections
2024-10-19 09:06:05.421 UTC [95] ERROR:  relation "app_config" does not exist at character 15
2024-10-19 09:06:05.421 UTC [95] STATEMENT:  select * from "app_config" limit $1
`

**Comment by mkaatman** [comment]
Same issue in proxmox lxc. app_config not setup correctly?

**Comment by johanohly** [comment]
This may very well be fixed by #76, which will be available in the next release. I'll let you know when it releases.

**Comment by johanohly** [comment]
v0.3.2 has just been released. Do let me know if this fixed the issue.

**Comment by mkaatman** [comment]
Fixed here.

**Comment by DevGoran** [comment]
Fixed for me. Thanks.

**Comment by johanohly** [comment]
Awesome, glad to hear it!

**Comment by lukasitaly** [comment]
Even though I'm running the latest version, the problem is still there for me. 

````bash
airtrail_db  | 2024-11-01 21:52:46.666 UTC [71] FATAL:  password authentication failed for user "airtrail"
airtrail_db  | 2024-11-01 21:52:46.666 UTC [71] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
airtrail     |       at /app/node_modules/pg-pool/index.js:45:11
airtrail     |
airtrail     | 40 |     res = resolve
airtrail     | 41 |     rej = reject
airtrail     | 42 |   }).catch((err) => {
airtrail     | 43 |     // replace the stack trace that leads to `TCP.onStreamRead` with one that leads back to the
airtrail     | 44 |     // application that created the query
airtrail     | 45 |     Error.captureStackTrace(err)
airtrail     |                ^
airtrail     | error: password authentication failed for user "airtrail"
airtrail     |  code: "28P01"
airtrail     |
airtrail     |       at /app/node_modules/pg-pool/index.js:45:11
```

**Comment by johanohly** [comment]
@lukasitaly that looks like your db credentials are mismatched. If you use the default docker-compose config, these two values need to be the same
![image](https://github.com/user-attachments/assets/b19d55c4-0512-4631-8b50-2994b3c9fed6)

**Comment by lukasitaly** [comment]
```yaml
# The database URL used by the application.
# If you are using the provided docker-compose file, you should only change the GJAVCXMWshKCnxzy
# If you are using your own database, you should change this to the correct URL
DB_URL=postgres://airtrail:GJAVCXMWshKCnxzy@db:5432/airtrail

# Values below this line are only for the default provided postgres database
###################################################################################
# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
# When you change the DB_PASSWORD, you should also update the DB_URL accordingly
DB_PASSWORD=GJAVCXMWshKCnxzy
```
I used the bash script to install AirTrail, and it seems like it was executed correctly, the credentials don't mismatch

**Comment by johanohly** [comment]
That is pretty weird. Can you show me your docker compose file and the first few lines of logs when starting docker compose? Including the database container starting.

(P.S. technically the password is just a formality in this case, as only other containers in the same compose file (or docker network) have access to the database as it isn't exposed)

**Comment by lukasitaly** [comment]
Compose:
```yaml
services:
  db:
    container_name: airtrail_db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}
      interval: 5s
      timeout: 5s
      retries: 5
  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data: null
networks: {}
```
Env:
```yaml
# Your domain, e.g https://example.com
# You might have to add :443 if you are using https through a reverse proxy
ORIGIN=http://192.168.1.66:3000

# The database URL used by the application.
# If you are using the provided docker-compose file, you should only change the GJAVCXMWshKCnxzy
# If you are using your own database, you should change this to the correct URL
DB_URL=postgres://airtrail:GJAVCXMWshKCnxzy@db:5432/airtrail

# Values below this line are only for the default provided postgres database
###################################################################################
# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
# When you change the DB_PASSWORD, you should also update the DB_URL accordingly
DB_PASSWORD=GJAVCXMWshKCnxzy

# The values below this line do not need to be changed
###################################################################################
DB_DATABASE_NAME=airtrail
DB_USERNAME=airtrail
```

Logs:
 ```bash
 airtrail     | Applying migrations...
airtrail     | Resolving dependencies
airtrail     | Resolved, downloaded and extracted [26]
airtrail     | Saved lockfile
airtrail     | Prisma schema loaded from prisma/schema.prisma
airtrail     | Datasource "db": PostgreSQL database "airtrail", schema "public" at "db:5432"
airtrail     | 
airtrail     | Error: P1000: Authentication failed against database server at `db`, the provided database credentials for `airtrail` are not valid.
airtrail     | 
airtrail     | Please make sure to provide valid database credentials for the database server at `db`.
airtrail     | Starting server...
airtrail     | Listening on 0.0.0.0:3000
airtrail     | 40 |     res = resolve
airtrail     | 41 |     rej = reject
airtrail     | 42 |   }).catch((err) => {
airtrail     | 43 |     // replace the stack trace that leads to `TCP.onStreamRead` with one that leads back to the
airtrail     | 44 |     // application that created the query
airtrail     | 45 |     Error.captureStackTrace(err)
airtrail     |                ^
airtrail     | error: password authentication failed for user "airtrail"
airtrail     |  code: "28P01"
airtrail     | 
airtrail     |       at /app/node_modules/pg-pool/index.js:45:11
airtrail     | 
airtrail     | 40 |     res = resolve
airtrail     | 41 |     rej = reject
airtrail     | 42 |   }).catch((err) => {
airtrail     | 43 |     // replace the stack trace that leads to `TCP.onStreamRead` with one that leads back to the
airtrail     | 44 |     // application that created the query
airtrail     | 45 |     Error.captureStackTrace(err)
airtrail     |                ^
airtrail     | error: password authentication failed for user "airtrail"
airtrail     |  code: "28P01"
airtrail     | 
airtrail     |       at /app/node_modules/pg-pool/index.js:45:11
airtrail     | 
airtrail     | 40 |     res = resolve
airtrail     | 41 |     rej = reject
airtrail     | 42 |   }).catch((err) => {
airtrail     | 43 |     // replace the stack trace that leads to `TCP.onStreamRead` with one that leads back to the
airtrail     | 44 |     // application that created the query
airtrail     | 45 |     Error.captureStackTrace(err)
airtrail     |                ^
airtrail     | error: password authentication failed for user "airtrail"
airtrail     |  code: "28P01"
airtrail     | 
airtrail     |       at /app/node_modules/pg-pool/index.js:45:11
airtrail     | 
airtrail     | 40 |     res = resolve
airtrail     | 41 |     rej = reject
airtrail     | 42 |   }).catch((err) => {
airtrail     | 43 |     // replace the stack trace that leads to `TCP.onStreamRead` with one that leads back to the
airtrail     | 44 |     // application that created the query
airtrail     | 45 |     Error.captureStackTrace(err)
airtrail     |                ^
airtrail     | error: password authentication failed for user "airtrail"
airtrail     |  code: "28P01"
airtrail     | 
airtrail     |       at /app/node_modules/pg-pool/index.js:45:11
airtrail     | 
airtrail_db  | 
airtrail_db  | PostgreSQL Database directory appears to contain a database; Skipping initialization
airtrail_db  | 
airtrail_db  | 2024-11-01 21:52:20.229 UTC [1] LOG:  starting PostgreSQL 16.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
airtrail_db  | 2024-11-01 21:52:20.229 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
airtrail_db  | 2024-11-01 21:52:20.229 UTC [1] LOG:  listening on IPv6 address "::", port 5432
airtrail_db  | 2024-11-01 21:52:20.237 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
airtrail_db  | 2024-11-01 21:52:20.248 UTC [28] LOG:  database system was shut down at 2024-11-01 21:52:09 UTC
airtrail_db  | 2024-11-01 21:52:20.258 UTC [1] LOG:  database system is ready to accept connections
airtrail_db  | 2024-11-01 21:52:32.206 UTC [46] FATAL:  password authentication failed for user "airtrail"
airtrail_db  | 2024-11-01 21:52:32.206 UTC [46] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
airtrail_db  | 2024-11-01 21:52:40.011 UTC [54] FATAL:  password authentication failed for user "airtrail"
airtrail_db  | 2024-11-01 21:52:40.011 UTC [54] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
airtrail_db  | 2024-11-01 21:52:42.278 UTC [63] FATAL:  password authentication failed for user "airtrail"
airtrail_db  | 2024-11-01 21:52:42.278 UTC [63] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
airtrail_db  | 2024-11-01 21:52:46.666 UTC [71] FATAL:  password authentication failed for user "airtrail"
airtrail_db  | 2024-11-01 21:52:46.666 UTC [71] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
airtrail_db  | 2024-11-01 21:54:55.582 UTC [252] FATAL:  password authentication failed for user "airtrail"
airtrail_db  | 2024-11-01 21:54:55.582 UTC [252] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
airtrail_db  | 2024-11-01 21:57:20.346 UTC [26] LOG:  checkpoint starting: time
airtrail_db  | 2024-11-01 21:57:20.374 UTC [26] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.008 s, sync=0.003 s, total=0.028 s; sync files=2, longest=0.002 s, average=0.002 s; distance=0 kB, estimate=0 kB; lsn=0/195C2C8, redo lsn=0/195C290
 ```
 Once I try to access the service via 192.168.1.66:3000:
 ```bash
airtrail_db  | 2024-11-01 22:27:22.655 UTC [3013] FATAL:  password authentication failed for user "airtrail"
airtrail_db  | 2024-11-01 22:27:22.655 UTC [3013] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
airtrail     | 40 |     res = resolve
airtrail     | 41 |     rej = reject
airtrail     | 42 |   }).catch((err) => {
airtrail     | 43 |     // replace the stack trace that leads to `TCP.onStreamRead` with one that leads back to the
airtrail     | 44 |     // application that created the query
airtrail     | 45 |     Error.captureStackTrace(err)
airtrail     |                ^
airtrail     | error: password authentication failed for user "airtrail"
airtrail     |  code: "28P01"
airtrail     | 
airtrail     |       at /app/node_modules/pg-pool/index.js:45:11
airtrail     | 
airtrail_db  | 2024-11-01 22:27:23.061 UTC [3014] FATAL:  password authentication failed for user "airtrail"
airtrail_db  | 2024-11-01 22:27:23.061 UTC [3014] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
airtrail     | 40 |     res = resolve
airtrail     | 41 |     rej = reject
airtrail     | 42 |   }).catch((err) => {
airtrail     | 43 |     // replace the stack trace that leads to `TCP.onStreamRead` with one that leads back to the
airtrail     | 44 |     // application that created the query
airtrail     | 45 |     Error.captureStackTrace(err)
airtrail     |                ^
airtrail     | error: password authentication failed for user "airtrail"
airtrail     |  code: "28P01"
airtrail     | 
airtrail     |       at /app/node_modules/pg-pool/index.js:45:11
airtrail     | 
 ```

**Comment by johanohly** [comment]
Using your exact configuration works on my machine. Can you send the beginning of the logs as well? They should contain the database startup logs which look something like this 
```
airtrail_db  | 
airtrail_db  | PostgreSQL Database directory appears to contain a database; Skipping initialization
airtrail_db  | 
airtrail_db  | 2024-11-01 22:36:21.438 UTC [1] LOG:  starting PostgreSQL 16.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
airtrail_db  | 2024-11-01 22:36:21.438 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
airtrail_db  | 2024-11-01 22:36:21.438 UTC [1] LOG:  listening on IPv6 address "::", port 5432
airtrail_db  | 2024-11-01 22:36:21.448 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
airtrail_db  | 2024-11-01 22:36:21.460 UTC [29] LOG:  database system was shut down at 2024-11-01 22:35:59 UTC
airtrail_db  | 2024-11-01 22:36:21.468 UTC [1] LOG:  database system is ready to accept connections
airtrail     | Applying migrations...
```

**Comment by lukasitaly** [comment]
Sure! Here you go:
```bash
airtrail  | Applying migrations...
airtrail  | Resolving dependencies
airtrail  | Resolved, downloaded and extracted [26]
airtrail  | Saved lockfile
airtrail_db  |
airtrail_db  | PostgreSQL Database directory appears to contain a database; Skipping initialization
airtrail_db  |
airtrail_db  | 2024-11-02 09:20:03.159 UTC [1] LOG:  starting PostgreSQL 16.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
airtrail_db  | 2024-11-02 09:20:03.159 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
airtrail_db  | 2024-11-02 09:20:03.159 UTC [1] LOG:  listening on IPv6 address "::", port 5432
airtrail_db  | 2024-11-02 09:20:03.166 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
airtrail_db  | 2024-11-02 09:20:03.176 UTC [29] LOG:  database system was shut down at 2024-11-01 23:01:43 UTC
airtrail_db  | 2024-11-02 09:20:03.186 UTC [1] LOG:  database system is ready to accept connections
lukas@lukas:/mnt/nasdrive/Server/airtrail$ docker compose logs
airtrail_db  |
airtrail_db  | PostgreSQL Database directory appears to contain a database; Skipping initialization
airtrail_db  |
airtrail_db  | 2024-11-02 09:20:03.159 UTC [1] LOG:  starting PostgreSQL 16.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
airtrail_db  | 2024-11-02 09:20:03.159 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
airtrail_db  | 2024-11-02 09:20:03.159 UTC [1] LOG:  listening on IPv6 address "::", port 5432
airtrail     | Applying migrations...
airtrail_db  | 2024-11-02 09:20:03.166 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
airtrail     | Resolving dependencies
airtrail     | Resolved, downloaded and extracted [26]
airtrail     | Saved lockfile
airtrail     | Prisma schema loaded from prisma/schema.prisma
airtrail     | Datasource "db": PostgreSQL database "airtrail", schema "public" at "db:5432"
airtrail     |
airtrail     | Error: P1000: Authentication failed against database server at `db`, the provided database credentials for `airtrail` are not valid.
airtrail     |
airtrail     | Please make sure to provide valid database credentials for the database server at `db`.
airtrail     | Starting server...
airtrail     | Listening on 0.0.0.0:3000
airtrail_db  | 2024-11-02 09:20:03.176 UTC [29] LOG:  database system was shut down at 2024-11-01 23:01:43 UTC
airtrail_db  | 2024-11-02 09:20:03.186 UTC [1] LOG:  database system is ready to accept connections
airtrail_db  | 2024-11-02 09:20:15.121 UTC [47] FATAL:  password authentication failed for user "airtrail"
airtrail_db  | 2024-11-02 09:20:15.121 UTC [47] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
```

**Comment by mkaatman** [comment]
error: password authentication failed for user "airtrail"
airtrail     |  code: "28P01"

Can you login to DB from cli directly?

**Comment by lukasitaly** [comment]
@mkaatman yes I was able to login to the DB from cli
